services:
  glpi-slack:
    build: .
    image: glpi-slack
    container_name: glpi-slack
    volumes:
      - ./logs:/app/logs
      - ./config.toml:/app/config.toml
    environment:
      - TZ=America/Chicago
    restart: unless-stopped
