version: '3'
services:
  app-glpi:
    build: .
    image: app-glpi
    container_name: app-glpi
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=America/Sao_Paulo
    restart: unless-stopped