services:
  glpi-slack:
    build: .
    image: glpi-slack
    container_name: glpi-slack
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - TZ=America/Chicago
    restart: unless-stopped